name: Deploy To Self Branch
on:
  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
      working-directory: bamba-admin-pwa
    - run: npm run build --if-present
      working-directory: bamba-admin-pwa
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        working-directory: bamba-admin-pwa
        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
