name: Deploy To Self Branch
on:
  push:	
    branches:	
      - master
  workflow_dispatch:

defaults:
  run:
    working-directory: bamba-admin-pwa

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: query ngrok tunnels
      id: query
      run: |
        response=$(curl -X GET -H "Authorization: Bearer ${{ secrets.NGROK_API_KEY }}" -H "Ngrok-Version: 2" https://api.ngrok.com/tunnels --insecure)
        echo $response
        echo $response > src/assets/tunnels.json
    - run: npm ci
      working-directory: bamba-admin-pwa
    - run: npm run build --if-present
      working-directory: bamba-admin-pwa
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: bamba-admin-pwa/dist
        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
